<?php
require __DIR__.'/../inc/bootstrap.php';
$q=trim((string)($_GET['q']??''));$loc=trim((string)($_GET['location']??''));$status=(int)($_GET['status']??0);$archived=(string)($_GET['archived']??'0');$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));$page=max(1,(int)($_GET['page']??1));$per=30;
$where=['1=1'];$params=[];
if($q!==''){$where[]='(a.tracking_code LIKE ? OR a.full_name LIKE ? OR a.email LIKE ?)';$like='%'.$q.'%';array_push($params,$like,$like,$like);}if($loc!==''&&isset(locations()[$loc])){$where[]='a.location=?';$params[]=$loc;}if($status>0){$where[]='a.current_status_id=?';$params[]=$status;}if($archived==='1')$where[]='a.is_archived=1';elseif($archived==='all'){}else $where[]='a.is_archived=0';if($from!==''){$where[]='DATE(a.created_at)>=?';$params[]=$from;}if($to!==''){$where[]='DATE(a.created_at)<=?';$params[]=$to;}
$sqlWhere=implode(' AND ',$where);$count=$db->prepare("SELECT COUNT(*) FROM applications a WHERE $sqlWhere");$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$per));$page=min($page,$pages);$offset=($page-1)*$per;
$stmt=$db->prepare("SELECT a.id,a.tracking_code,a.full_name,a.email,a.location,a.is_archived,a.created_at,s.name status_name,s.display_color status_color FROM applications a LEFT JOIN statuses s ON s.id=a.current_status_id WHERE $sqlWhere ORDER BY a.created_at DESC LIMIT $per OFFSET $offset");$stmt->execute($params);$rows=$stmt->fetchAll();$statuses=$db->query('SELECT * FROM statuses ORDER BY name')->fetchAll();
$adminTitle='Applications';require __DIR__.'/_header.php';
$queryBase=$_GET;unset($queryBase['page']);
?>
<section class="panel"><form method="get" class="filters"><div class="field search"><label>Search</label><input name="q" value="<?=h($q)?>" placeholder="Tracking code, name, or email"></div><div class="field"><label>Location</label><select name="location"><option value="">All</option><?php foreach(locations() as $k=>$v):?><option value="<?=h($k)?>" <?=$loc===$k?'selected':''?>><?=h($v)?></option><?php endforeach;?></select></div><div class="field"><label>Status</label><select name="status"><option value="0">All</option><?php foreach($statuses as $s):?><option value="<?=$s['id']?>" <?=$status==(int)$s['id']?'selected':''?>><?=h($s['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Archive</label><select name="archived"><option value="0" <?=$archived==='0'?'selected':''?>>Active only</option><option value="1" <?=$archived==='1'?'selected':''?>>Archived only</option><option value="all" <?=$archived==='all'?'selected':''?>>All</option></select></div><div class="field"><label>From</label><input type="date" name="from" value="<?=h($from)?>"></div><div class="field"><label>To</label><input type="date" name="to" value="<?=h($to)?>"></div><button class="btn btn-primary">Filter</button><a class="btn btn-secondary" href="applications.php">Reset</a></form></section>
<section class="panel"><div class="panel-head"><div><h2 style="margin:0">Applications</h2><span class="muted"><?=$total?> result<?= $total===1?'':'s'?></span></div><a class="btn btn-secondary" href="export.php?<?=h(http_build_query($_GET))?>">Export CSV</a></div><div class="table-wrap"><table class="table"><thead><tr><th>Tracking code</th><th>Applicant</th><th>Location</th><th>Status</th><th>Received</th><th></th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="6" class="empty">No applications match these filters.</td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td class="code"><?=h($r['tracking_code'])?><?= $r['is_archived']?'<br><span class="muted">Archived</span>':''?></td><td><strong><?=h($r['full_name'])?></strong><br><span class="muted"><?=h($r['email'])?></span></td><td><?=h(location_label($r['location']))?></td><td><?php if($r['status_name']):?><span class="badge" style="background:<?=h($r['status_color'])?>"><?=h($r['status_name'])?></span><?php else:?><span class="muted">No status</span><?php endif;?></td><td><?=h(date('M j, Y g:i A',strtotime($r['created_at'])))?></td><td><a href="application.php?id=<?=$r['id']?>">View →</a></td></tr><?php endforeach;?></tbody></table></div><?php if($pages>1):?><div class="pagination"><?php for($i=1;$i<=$pages;$i++):$u=$queryBase;$u['page']=$i;?><a class="<?=$i===$page?'active':''?>" href="?<?=h(http_build_query($u))?>"><?=$i?></a><?php endfor;?></div><?php endif;?></section>
<?php require __DIR__.'/_footer.php';?>
