<?php
require __DIR__.'/../inc/bootstrap.php';
$id=(int)($_GET['id']??$_POST['id']??0);$stmt=$db->prepare('SELECT a.*,s.name status_name,s.display_color status_color,f.title form_title FROM applications a LEFT JOIN statuses s ON s.id=a.current_status_id LEFT JOIN forms f ON f.id=a.form_id WHERE a.id=? LIMIT 1');$stmt->execute([$id]);$app=$stmt->fetch();if(!$app){http_response_code(404);exit('Application not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';
 if($action==='add_update'){
   $title=trim((string)($_POST['title']??''));$message=trim((string)($_POST['message']??''));$statusId=(int)($_POST['status_id']??0);$linkLabel=trim((string)($_POST['link_label']??''));$linkUrl=trim((string)($_POST['link_url']??''));
   if(!$title){flash('error','Update title is required.');redirect('gadmin8f3k2p9x7m4q6v1c/application.php?id='.$id);}if($linkUrl!==''&&!safe_return_url($linkUrl)){flash('error','Links must use a valid https:// URL.');redirect('gadmin8f3k2p9x7m4q6v1c/application.php?id='.$id);}
   $db->beginTransaction();try{$statusName=null;$statusColor=null;if($statusId){$ss=$db->prepare('SELECT name,display_color FROM statuses WHERE id=?');$ss->execute([$statusId]);$sr=$ss->fetch();if($sr){$statusName=$sr['name'];$statusColor=$sr['display_color'];}else{$statusId=0;}}$ins=$db->prepare("INSERT INTO application_updates(application_id,status_id,status_name_snapshot,status_color_snapshot,actor_type,title,message,link_label,link_url) VALUES (?,?,?,?,'admin',?,?,?,?)");$ins->execute([$id,$statusId?:null,$statusName,$statusColor,$title,$message,$linkLabel?:null,$linkUrl?:null]);if($statusId){$db->prepare('UPDATE applications SET current_status_id=? WHERE id=?')->execute([$statusId,$id]);}$db->commit();$emailSent=send_update_email($app,['title'=>$title,'message'=>$message,'link_label'=>$linkLabel,'link_url'=>$linkUrl]);flash($emailSent?'success':'error',$emailSent?'Application update saved and email notification sent.':'Application update saved, but the email could not be sent. '.mail_last_error());}catch(Throwable $e){if($db->inTransaction())$db->rollBack();flash('error','Could not save update.');}redirect('gadmin8f3k2p9x7m4q6v1c/application.php?id='.$id);
 }
 if($action==='resend_confirmation'){$ok=send_application_confirmation($app);flash($ok?'success':'error',$ok?'Confirmation email sent successfully.':'Confirmation email could not be sent. '.mail_last_error());redirect('gadmin8f3k2p9x7m4q6v1c/application.php?id='.$id);}
 if($action==='toggle_archive'){$new=$app['is_archived']?0:1;$db->prepare('UPDATE applications SET is_archived=? WHERE id=?')->execute([$new,$id]);flash('success',$new?'Application archived.':'Application restored.');redirect('gadmin8f3k2p9x7m4q6v1c/application.php?id='.$id);}
 if($action==='delete'){$files=$db->prepare('SELECT stored_name FROM application_files WHERE application_id=?');$files->execute([$id]);foreach($files->fetchAll() as $f){$p=UPLOAD_PATH.'/'.$f['stored_name'];if(is_file($p))@unlink($p);}$db->prepare('DELETE FROM applications WHERE id=?')->execute([$id]);flash('success','Application permanently deleted.');redirect('gadmin8f3k2p9x7m4q6v1c/applications.php');}
}
$statuses=$db->query('SELECT * FROM statuses ORDER BY name')->fetchAll();$updates=$db->prepare('SELECT u.*,COALESCE(u.status_name_snapshot,s.name) status_name,COALESCE(u.status_color_snapshot,s.display_color) status_color FROM application_updates u LEFT JOIN statuses s ON s.id=u.status_id WHERE u.application_id=? ORDER BY u.created_at DESC,u.id DESC');$updates->execute([$id]);$updates=$updates->fetchAll();$files=$db->prepare('SELECT * FROM application_files WHERE application_id=? ORDER BY created_at');$files->execute([$id]);$allFiles=$files->fetchAll();$filesByUpdate=[];$initialFiles=[];foreach($allFiles as $f){if($f['update_id'])$filesByUpdate[$f['update_id']][]=$f;else $initialFiles[]=$f;}$answers=json_decode($app['answers_json'],true)?:[];$snapshot=json_decode($app['form_snapshot_json'],true)?:[];$labels=[];foreach($snapshot['fields']??[] as $f)$labels[$f['field_key']]=$f['label'];
$adminTitle='Application '.$app['tracking_code'];require __DIR__.'/_header.php';
?>
<div class="panel"><div class="panel-head"><div><a href="applications.php">← Applications</a><h2 style="margin:8px 0 0"><?=h($app['full_name'])?></h2><div class="code"><?=h($app['tracking_code'])?></div></div><div class="actions"><?php if($app['status_name']):?><span class="badge" style="background:<?=h($app['status_color'])?>"><?=h($app['status_name'])?></span><?php else:?><span class="muted">No status</span><?php endif;?></div></div><div class="answer-grid"><div class="answer"><b>Email</b><a href="mailto:<?=h($app['email'])?>"><?=h($app['email'])?></a></div><div class="answer"><b>Location</b><?=h(location_label($app['location']))?></div><div class="answer"><b>Application form</b><?=h($app['form_title']?:($snapshot['title']??'Deleted form'))?> · v<?= (int)$app['form_version']?></div><div class="answer"><b>Submitted</b><?=h(date('F j, Y · g:i A',strtotime($app['created_at'])))?></div></div></div>
<div class="grid-2"><section class="panel"><h3>Application answers</h3><?php if(!$answers):?><div class="empty">No custom answers.</div><?php else:?><div class="answer-grid"><?php foreach($answers as $key=>$value):?><div class="answer"><b><?=h($labels[$key]??$key)?></b><?=is_array($value)?h(implode(', ',$value)):nl2br(h((string)$value))?></div><?php endforeach;?></div><?php endif;?><?php if($initialFiles):?><h3 style="margin-top:22px">Submitted files</h3><?php foreach($initialFiles as $file):?><p><a href="download.php?id=<?=$file['id']?>">📎 <?=h($labels[$file['field_key']]??$file['field_key']??'File')?> — <?=h($file['original_name'])?></a> <span class="muted">(<?=number_format($file['file_size']/1024/1024,2)?> MB)</span></p><?php endforeach;?><?php endif;?></section>
<section class="panel"><h3>Add application update</h3><?php if(!$statuses):?><div class="notice">No statuses exist yet. You can still add a message, or <a href="statuses.php">create statuses first</a>.</div><?php endif;?><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="add_update"><div class="form-grid"><div class="field full"><label>Status <span class="muted">(optional)</span></label><select name="status_id"><option value="0">Do not change status</option><?php foreach($statuses as $s):?><option value="<?=$s['id']?>"><?=h($s['name'])?></option><?php endforeach;?></select></div><div class="field full"><label>Update title</label><input name="title" placeholder="e.g. Additional information required" required></div><div class="field full"><label>Message</label><textarea name="message" placeholder="Explain the update to the applicant"></textarea></div><div class="field"><label>Button/link label</label><input name="link_label" placeholder="e.g. Continue application"></div><div class="field"><label>HTTPS link</label><input type="url" name="link_url" placeholder="https://..."></div><div class="field full"><button class="btn btn-primary">Save Update & Notify Applicant</button></div></div></form></section></div>
<section class="panel"><h3>Complete update history</h3><div class="timeline"><?php foreach($updates as $u):?><article class="timeline-item"><h4><?=h($u['title'])?> <?php if($u['status_name']):?><span class="badge" style="background:<?=h($u['status_color'])?>"><?=h($u['status_name'])?></span><?php endif;?></h4><div class="meta"><?=h(date('F j, Y · g:i A',strtotime($u['created_at'])))?> · <?=h(ucfirst($u['actor_type']))?></div><?php if($u['message']):?><p><?=nl2br(h($u['message']))?></p><?php endif;?><?php if($u['link_url']):?><p><a target="_blank" rel="noopener" href="<?=h($u['link_url'])?>"><?=h($u['link_label']?:$u['link_url'])?> ↗</a></p><?php endif;?><?php foreach($filesByUpdate[$u['id']]??[] as $file):?><p><a href="download.php?id=<?=$file['id']?>">📎 <?=h($file['original_name'])?></a></p><?php endforeach;?></article><?php endforeach;?></div></section>
<section class="panel danger-zone"><h3>Application controls</h3><div class="actions"><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="resend_confirmation"><button class="btn btn-secondary">Resend Confirmation Email</button></form><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="toggle_archive"><button class="btn btn-secondary"><?=$app['is_archived']?'Restore application':'Archive application'?></button></form><form method="post" onsubmit="return confirm('Permanently delete this application and all uploaded files? This cannot be undone.')"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="delete"><button class="btn btn-danger">Permanently Delete</button></form></div></section>
<?php require __DIR__.'/_footer.php';?>
