<?php
require __DIR__.'/../inc/bootstrap.php';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';
 if($action==='create'){
  $title=trim((string)($_POST['title']??''));$location=(string)($_POST['location']??'');$description=trim((string)($_POST['description']??''));$active=isset($_POST['is_active'])?1:0;
  if(!$title||!isset(locations()[$location])){flash('error','Enter a form title and valid location.');redirect('gadmin8f3k2p9x7m4q6v1c/forms.php');}
  $db->beginTransaction();try{if($active)$db->prepare('UPDATE forms SET is_active=0 WHERE location=?')->execute([$location]);$stmt=$db->prepare('INSERT INTO forms(location,title,description,is_active) VALUES(?,?,?,?)');$stmt->execute([$location,$title,$description,$active]);$id=(int)$db->lastInsertId();$db->commit();flash('success','Form created. Add the fields now.');redirect('gadmin8f3k2p9x7m4q6v1c/form-edit.php?id='.$id);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();flash('error','Could not create form.');}
 }
 if($action==='delete'){$id=(int)($_POST['id']??0);$db->prepare('DELETE FROM forms WHERE id=?')->execute([$id]);flash('success','Form deleted. Existing applications keep their saved form snapshot.');redirect('gadmin8f3k2p9x7m4q6v1c/forms.php');}
 if($action==='activate'){$id=(int)($_POST['id']??0);$st=$db->prepare('SELECT location FROM forms WHERE id=?');$st->execute([$id]);$loc=$st->fetchColumn();if($loc){$db->beginTransaction();$db->prepare('UPDATE forms SET is_active=0 WHERE location=?')->execute([$loc]);$db->prepare('UPDATE forms SET is_active=1 WHERE id=?')->execute([$id]);$db->commit();flash('success','Form activated.');}redirect('gadmin8f3k2p9x7m4q6v1c/forms.php');}
}
$forms=$db->query('SELECT f.*,(SELECT COUNT(*) FROM form_fields ff WHERE ff.form_id=f.id) field_count,(SELECT COUNT(*) FROM applications a WHERE a.form_id=f.id) application_count FROM forms f ORDER BY FIELD(f.location,"usa","uk","canada","australia","others"),f.created_at DESC')->fetchAll();$adminTitle='Forms';require __DIR__.'/_header.php';
?>
<section class="panel"><h2>Create application form</h2><p class="muted">Full Name and Email Address are automatically included in every form and cannot be removed.</p><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="create"><div class="form-grid"><div class="field"><label>Form title</label><input name="title" placeholder="e.g. USA General Grant Application" required></div><div class="field"><label>Location</label><select name="location" required><?php foreach(locations() as $k=>$v):?><option value="<?=h($k)?>"><?=h($v)?></option><?php endforeach;?></select></div><div class="field full"><label>Description <span class="muted">(optional)</span></label><textarea name="description" style="min-height:75px"></textarea></div><div class="field full"><label><input type="checkbox" name="is_active" value="1"> Make this the active form for this location</label><small>Only one form can be active per location at a time.</small></div><div class="field full"><button class="btn btn-primary">Create Form</button></div></div></form></section>
<section class="panel"><h2>Application forms</h2><div class="table-wrap"><table class="table"><thead><tr><th>Title</th><th>Location</th><th>Version</th><th>Fields</th><th>Applications</th><th>State</th><th></th></tr></thead><tbody><?php if(!$forms):?><tr><td colspan="7" class="empty">No forms created yet.</td></tr><?php endif;?><?php foreach($forms as $f):?><tr><td><strong><?=h($f['title'])?></strong></td><td><?=h(location_label($f['location']))?></td><td>v<?=$f['version']?></td><td><?=2+(int)$f['field_count']?> total</td><td><?=$f['application_count']?></td><td><?= $f['is_active']?'<span class="badge" style="background:#1d7a4d">Active</span>':'<span class="muted">Inactive</span>'?></td><td><div class="actions"><a class="btn btn-secondary btn-small" href="form-edit.php?id=<?=$f['id']?>">Edit</a><?php if(!$f['is_active']):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="activate"><input type="hidden" name="id" value="<?=$f['id']?>"><button class="btn btn-secondary btn-small">Activate</button></form><?php endif;?><form method="post" onsubmit="return confirm('Delete this form? Existing applications will keep their saved form snapshot.')"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$f['id']?>"><button class="btn btn-danger btn-small">Delete</button></form></div></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require __DIR__.'/_footer.php';?>
