<?php
require __DIR__.'/../inc/bootstrap.php';
$total=(int)$db->query('SELECT COUNT(*) FROM applications')->fetchColumn();
$active=(int)$db->query('SELECT COUNT(*) FROM applications WHERE is_archived=0')->fetchColumn();
$today=(int)$db->query('SELECT COUNT(*) FROM applications WHERE DATE(created_at)=CURDATE()')->fetchColumn();
$contacts=(int)$db->query('SELECT COUNT(*) FROM contact_messages WHERE is_read=0')->fetchColumn();
$byStatus=$db->query('SELECT COALESCE(s.name,"No status") name,COALESCE(s.display_color,"#71838c") color,COUNT(*) total FROM applications a LEFT JOIN statuses s ON s.id=a.current_status_id GROUP BY a.current_status_id,s.name,s.display_color ORDER BY total DESC')->fetchAll();
$byLocation=$db->query('SELECT location,COUNT(*) total FROM applications GROUP BY location ORDER BY total DESC')->fetchAll();
$recent=$db->query('SELECT a.id,a.tracking_code,a.full_name,a.email,a.location,a.created_at,s.name status_name,s.display_color status_color FROM applications a LEFT JOIN statuses s ON s.id=a.current_status_id ORDER BY a.created_at DESC LIMIT 10')->fetchAll();
$adminTitle='Dashboard';require __DIR__.'/_header.php';
?>
<div class="stats"><div class="stat"><span>Total applications</span><strong><?=$total?></strong></div><div class="stat"><span>Active applications</span><strong><?=$active?></strong></div><div class="stat"><span>Received today</span><strong><?=$today?></strong></div><div class="stat"><span>Unread messages</span><strong><?=$contacts?></strong></div></div>
<div class="grid-2"><section class="panel"><h3>Applications by status</h3><?php if(!$byStatus):?><div class="empty">No applications yet.</div><?php else:?><table class="table"><?php foreach($byStatus as $r):?><tr><td><span class="color-chip" style="background:<?=h($r['color'])?>"></span><?=h($r['name'])?></td><td><strong><?=$r['total']?></strong></td></tr><?php endforeach;?></table><?php endif;?></section><section class="panel"><h3>Applications by location</h3><?php if(!$byLocation):?><div class="empty">No applications yet.</div><?php else:?><table class="table"><?php foreach($byLocation as $r):?><tr><td><?=h(location_label($r['location']))?></td><td><strong><?=$r['total']?></strong></td></tr><?php endforeach;?></table><?php endif;?></section></div>
<section class="panel"><div class="panel-head"><h3 style="margin:0">Recent applications</h3><a class="btn btn-secondary" href="applications.php">View all</a></div><div class="table-wrap"><table class="table"><thead><tr><th>Tracking code</th><th>Applicant</th><th>Location</th><th>Status</th><th>Received</th><th></th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td class="code"><?=h($r['tracking_code'])?></td><td><strong><?=h($r['full_name'])?></strong><br><span class="muted"><?=h($r['email'])?></span></td><td><?=h(location_label($r['location']))?></td><td><?php if($r['status_name']):?><span class="badge" style="background:<?=h($r['status_color'])?>"><?=h($r['status_name'])?></span><?php else:?><span class="muted">No status</span><?php endif;?></td><td><?=h(date('M j, Y',strtotime($r['created_at'])))?></td><td><a href="application.php?id=<?=$r['id']?>">Open →</a></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require __DIR__.'/_footer.php';?>
