<?php
require __DIR__.'/../inc/bootstrap.php';
$generalKeys=['program_name','homepage_headline','homepage_subtitle','public_email','public_phone','whatsapp_url','organization_location','about_text','privacy_text','terms_text'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';
 if($action==='save_general'){foreach($generalKeys as $key)set_setting($key,trim((string)($_POST[$key]??'')));flash('success','Website settings saved.');redirect('gadmin8f3k2p9x7m4q6v1c/settings.php');}
 if($action==='save_email'){foreach(['smtp_host','smtp_port','smtp_encryption','smtp_username','smtp_from_email','smtp_from_name'] as $key)set_setting($key,trim((string)($_POST[$key]??'')));$newPass=(string)($_POST['smtp_password']??'');if($newPass!=='')set_setting('smtp_password',encrypt_secret($newPass));flash('success','Email settings saved.');redirect('gadmin8f3k2p9x7m4q6v1c/settings.php');}
 if($action==='test_email'){$to=trim((string)($_POST['test_email']??''));if(!filter_var($to,FILTER_VALIDATE_EMAIL)){flash('error','Enter a valid test email address.');}else{$ok=mail_html($to,'EmpowerME email test',email_shell('Email configuration test','<p>Your EmpowerME SMTP settings are working.</p>'),null,'smtp_test');flash($ok?'success':'error',$ok?'Test email sent successfully.':'The test email could not be sent. '.mail_last_error());}redirect('gadmin8f3k2p9x7m4q6v1c/settings.php');}
}
$adminTitle='Settings & Email';require __DIR__.'/_header.php';
?>
<section class="panel"><h2>Website & organization</h2><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="save_general"><div class="form-grid"><div class="field"><label>Program name</label><input name="program_name" value="<?=h(setting('program_name'))?>"></div><div class="field"><label>Organization location</label><input name="organization_location" value="<?=h(setting('organization_location'))?>"></div><div class="field full"><label>Homepage headline</label><input name="homepage_headline" value="<?=h(setting('homepage_headline'))?>"></div><div class="field full"><label>Homepage subtitle</label><textarea name="homepage_subtitle" style="min-height:75px"><?=h(setting('homepage_subtitle'))?></textarea></div><div class="field"><label>Public email</label><input type="email" name="public_email" value="<?=h(setting('public_email'))?>"></div><div class="field"><label>Public phone / WhatsApp</label><input name="public_phone" value="<?=h(setting('public_phone'))?>"></div><div class="field full"><label>WhatsApp inquiry URL</label><input type="url" name="whatsapp_url" value="<?=h(setting('whatsapp_url'))?>"></div><div class="field full"><label>About page text</label><textarea name="about_text"><?=h(setting('about_text'))?></textarea></div><div class="field full"><label>Privacy page content</label><textarea name="privacy_text"><?=h(setting('privacy_text'))?></textarea></div><div class="field full"><label>Terms page content</label><textarea name="terms_text"><?=h(setting('terms_text'))?></textarea></div><div class="field full"><button class="btn btn-primary">Save Website Settings</button></div></div></form></section>
<section class="panel"><h2>Email / SMTP setup</h2><p class="muted">Application confirmations, status-update notifications, contact alerts, and applicant-response alerts use these settings. The SMTP password is encrypted with the application key before it is stored in MySQL.</p><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="save_email"><div class="form-grid"><div class="field"><label>SMTP host</label><input name="smtp_host" value="<?=h(setting('smtp_host'))?>" placeholder="mail.example.com"></div><div class="field"><label>SMTP port</label><input type="number" name="smtp_port" value="<?=h(setting('smtp_port','587'))?>"></div><div class="field"><label>Encryption</label><select name="smtp_encryption"><option value="tls" <?=setting('smtp_encryption')==='tls'?'selected':''?>>TLS / STARTTLS</option><option value="ssl" <?=setting('smtp_encryption')==='ssl'?'selected':''?>>SSL</option><option value="none" <?=setting('smtp_encryption')==='none'?'selected':''?>>None</option></select></div><div class="field"><label>SMTP username</label><input name="smtp_username" value="<?=h(setting('smtp_username'))?>"></div><div class="field"><label>SMTP password</label><input type="password" name="smtp_password" placeholder="Leave blank to keep current password"><small><?=setting('smtp_password')?'A password is currently saved.':'No password is saved yet.'?></small></div><div class="field"><label>Sender email</label><input type="email" name="smtp_from_email" value="<?=h(setting('smtp_from_email'))?>"></div><div class="field"><label>Sender name</label><input name="smtp_from_name" value="<?=h(setting('smtp_from_name',setting('program_name')))?>"></div><div class="field full"><button class="btn btn-primary">Save Email Settings</button></div></div></form><hr style="border:0;border-top:1px solid var(--line);margin:24px 0"><form method="post" class="filters"><?=csrf_field()?><input type="hidden" name="action" value="test_email"><div class="field search"><label>Send test email to</label><input type="email" name="test_email" placeholder="you@example.com" required></div><button class="btn btn-secondary">Send Test Email</button></form></section>
<?php require __DIR__.'/_footer.php';?>
