<?php
require __DIR__.'/../inc/bootstrap.php';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';$id=(int)($_POST['id']??0);
 if($action==='save'){$name=trim((string)($_POST['name']??''));$color=trim((string)($_POST['color']??'#064f78'));if(!$name){flash('error','Status name is required.');}elseif(!preg_match('/^#[0-9A-Fa-f]{6}$/',$color)){flash('error','Choose a valid status color.');}else{if($id){$db->prepare('UPDATE statuses SET name=?,display_color=? WHERE id=?')->execute([$name,$color,$id]);flash('success','Status updated.');}else{$db->prepare('INSERT INTO statuses(name,display_color) VALUES(?,?)')->execute([$name,$color]);flash('success','Status created.');}}redirect('gadmin8f3k2p9x7m4q6v1c/statuses.php');}
 if($action==='delete'&&$id){$db->prepare('DELETE FROM statuses WHERE id=?')->execute([$id]);flash('success','Status deleted. Applications that used it now have no current status; the text of existing updates is preserved.');redirect('gadmin8f3k2p9x7m4q6v1c/statuses.php');}
}
$statuses=$db->query('SELECT s.*,(SELECT COUNT(*) FROM applications a WHERE a.current_status_id=s.id) application_count FROM statuses s ORDER BY s.created_at')->fetchAll();$edit=null;if(isset($_GET['edit'])){$st=$db->prepare('SELECT * FROM statuses WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
$adminTitle='Statuses';require __DIR__.'/_header.php';
?>
<div class="grid-2"><section class="panel"><h2><?= $edit?'Edit status':'Create status'?></h2><p class="muted">There are no built-in grant statuses. Create the stages you want to use.</p><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0)?>"><div class="field"><label>Status name</label><input name="name" value="<?=h($edit['name']??'')?>" placeholder="e.g. Under Review" required></div><div class="field" style="margin-top:14px"><label>Display color</label><input type="color" name="color" value="<?=h($edit['display_color']??'#064f78')?>" style="height:44px;padding:4px"></div><p><button class="btn btn-primary"><?= $edit?'Save Changes':'Create Status'?></button><?php if($edit):?> <a class="btn btn-secondary" href="statuses.php">Cancel</a><?php endif;?></p></form></section><section class="panel"><h2>Current statuses</h2><?php if(!$statuses):?><div class="empty">No statuses created yet.</div><?php else:?><table class="table"><thead><tr><th>Status</th><th>Applications</th><th></th></tr></thead><tbody><?php foreach($statuses as $s):?><tr><td><span class="color-chip" style="background:<?=h($s['display_color'])?>"></span><strong><?=h($s['name'])?></strong></td><td><?=$s['application_count']?></td><td><div class="actions"><a class="btn btn-secondary btn-small" href="?edit=<?=$s['id']?>">Edit</a><form method="post" onsubmit="return confirm('Delete this status?')"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$s['id']?>"><button class="btn btn-danger btn-small">Delete</button></form></div></td></tr><?php endforeach;?></tbody></table><?php endif;?></section></div>
<?php require __DIR__.'/_footer.php';?>
